version: '3.4'

services:
  fbs.api:
    image: ${DOCKER_REGISTRY-}fbsapi
    build:
      context: .
      dockerfile: FBS.API/Dockerfile
    ports:
      - "8085:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__FootballCourtBooking=Server=sqlserverdb;Database=FootballCourtBooking;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserverdb
    networks:
      - backend
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
      - MSSQL_USER=sa
    ports:
      - "1436:1433"
    networks:
      - backend
    volumes:
      - sqlserverdata:/var/opt/mssql

networks:
  backend:
    driver: bridge
volumes:
  sqlserverdata:

